# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0/10 * * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: |
        python ../main.py
        
        
